### ISSUE TITLE
Masterlist Update broken

### ISSUE THREAD

**Issue by chrschmidt** [niveuseverto/fomm#1]
Hi,

The Masterlist update needed for BOSS is broken.
http://better-oblivion-sorting-software.googlecode.com/svn/data/boss-fallout/masterlist.txt
now requires a login, which is apparently non-public, not even with a google account. This causes FOMM to crashdump. Maybe you could re-host this file here on github?

Best regards,
Christian

Fomm 0.13.23
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (401) Nicht autorisiert.
   bei System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   bei System.Net.WebClient.DownloadString(Uri address)
   bei System.Net.WebClient.DownloadString(String address)
   bei Fomm.Games.Fallout3.Tools.AutoSorter.Fallout3BOSSUpdater.GetMasterlistVersion()

Sorry for German error messages, but microsoft apparently has the need to translate everything.

**Comment by niveuseverto** [comment]
We'll soon move to LOOT, so stay in touch.

**Comment by niveuseverto** [comment]
Will be fixed with #7
