### ISSUE TITLE
Crashes at start up

### ISSUE THREAD

**Issue by FRiNGE07** [niveuseverto/fomm#10]
same problem I had before It crashes when it loads the game I selected
Edit: Forgot to read the readme.txt lol I have to set the install path.

EDit tried adding it to the game install dir and I still get crashes

**Comment by niveuseverto** [comment]
Do you still have this issue?

**Comment by niveuseverto** [comment]
Released here and on NexusMods latest version. If problem persists, feel free to reopen this issue.
