### ISSUE TITLE
Unexpected node type

### ISSUE THREAD

**Issue by RoyBatty64** [niveuseverto/fomm#11]
The mod oHud gives the error "Unexpected node type" in info.xml when opening the package manager.

**Comment by niveuseverto** [comment]
Please, let me link to this mod, to check if everything is working correctly

**Comment by EvilOssie** [comment]
oHud NV link - http://www.nexusmods.com/newvegas/mods/44757/?

**Comment by niveuseverto** [comment]
Just checked, oHud archive doesn't contain info.xml by default (at least both v1.1).

@RoyBatty64 do you use NMM in any way?

**Comment by RoyBatty64** [comment]
oHud had since been updated and this is no longer an issue.

No I don't use NMM in any way, and I don't use FOMM anymore either. I
switched to MO.

**Comment by niveuseverto** [comment]
Checked earlier version. There is no issue now.

Could you please describe why is MO better than FOMM?

**Comment by RoyBatty64** [comment]
1. Profiling
2. The virtual file system allows for easy asset conflict resolution
3. The virtual file system allows for keeping a clean base installation
4. The virtual file system removes any need to uninstall mods in the order
they were installed, as each mod is kept entirely separate and enabled at
run time
5. Runtime only .ini alterations
6. BSA management and priority

FOMM still has useful tools, but they need better UI's, like the BSA
management tools. Additionally the BSA creator is slow.

**Comment by niveuseverto** [comment]
Did he managed to fix issues to install complex mods like Unified HUD?
Last time I checked MO it was unable to install it...

**Comment by RoyBatty64** [comment]
MO now has script support.

uHUD isn't any longer needed because of UIO by jazzisparis, but users can
still use it if they wish.
