### ISSUE TITLE
Can't start Fallout 3

### ISSUE THREAD

**Issue by fschmill** [niveuseverto/fomm#12]
I have the german version of Fallout 3 and i start FOMM, but if i click the "Launch Fallout 3"-button nothing happens. Fallout 3 run wihtout fomm.

fomm.0.14.10.2 is the last version that works for me.

P.S. Sorry for my weird English.

**Comment by niveuseverto** [comment]
Sorry for late reply.

Please note me, if this problem persists.

**Comment by niveuseverto** [comment]
Released here and on NexusMods latest version. If problem persists, feel free to reopen this issue.
