### ISSUE TITLE
Problems when fetching new masterlist. Help!

### ISSUE THREAD

**Issue by S4MW1CH** [niveuseverto/fomm#15]
everytime i try to fetch a masterlist for BOSS this message appears ( idk if it's translated well,i speak spanish)...
There Was an error updating BOSS
Error in remote server: (401) not authorized
the original message said:
There was an error updating BOSS
Error en el servidor remoto: (401) no autorizado.
(english and spanish got mixed in the message)
by the way if this explains anything,i'm using Windows 8.
Hope you can help me :c

**Comment by niveuseverto** [comment]
We will be integrating with LOOT soon, so this option will be working again.

**Comment by niveuseverto** [comment]
Will be fixed with #7
