### ISSUE TITLE
Fomm crashes during ALL installs, reactivations

### ISSUE THREAD

**Issue by Nofsdad** [niveuseverto/fomm#20]
For the past couple  of days I have been unable to install with FOMM, either in FO3 or FNV.  I goes through the entire process of installing the mod, then crashes with an error message saying file already exists.  Does it when installing a new mod or reactivating an old one.
Using the latest version, had been working since July with no problems, made no changes to my FOMM installation.
Others are having the same problem and the author has disappeared again.  Kind of wish he'd let someone take it over who's able to maintain or support it.

**Comment by niveuseverto** [comment]
Is this problem persists?

**Comment by niveuseverto** [comment]
Released here and on NexusMods latest version. If problem persists, feel free to reopen this issue.
