### ISSUE TITLE
BOSS Error 401

### ISSUE THREAD

**Issue by ZuluOverlord978** [niveuseverto/fomm#31]
I just had it today and never had this problem for over a year. Is this a temporary thing that I should not be worried about or do you need to send some sort of fix for it.

**Comment by niveuseverto** [comment]
This is permanent thing now as BOSS is deprecated.

Can you please give me a hint, what version do you use?

**Comment by ZuluOverlord978** [comment]
The latest version but it resolved itself though; thanks for replying by
the way.

**Comment by niveuseverto** [comment]
Ok, then, I'm closing this issue as #7 is about replacing deprecated BOSS with brand new LOOT
